! Default animation profile
!
! Valid ease values:
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! NONE
! LINEAR
! EASE_OUT
! EASE_IN
! ELASTIC
! BOUNCE
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


%anim 
    ease        : EASE_IN
    speed       : 0.20
    overshoot   : 2000.00
    stiffness   : 0.50
    damping     : 0.75
%anim