%settings
    USER_TERMINAL_POSIX : kitty
    USER_TERMINAL_WIN32 : pwsh.exe
    PALETTE             : Malmo

! AVAILABLE CURSOR MACROS
!
! UNDESCORE
! BOX
! HOLLOW
! LINE
!
    CURSOR_SYMBOL            : LINE

! FROM options/anim/ 
! 
! ie file/animation.conf will need to be file/animation in the settings file option
! 
    ANIM_CURSOR_PROFILE      : cursor/ease
    ANIM_CONSOLE_PROFILE     : console/ease
    ANIM_FQ_PROFILE          : fq/ease
%settings